using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCompanyAttribute("TestCompany")]
[assembly: AssemblyVersionAttribute("0.0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.0.1")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0.d55dc76ae63f920c06d34764852c32eb0cf55e3f")]
[assembly: AssemblyTitleAttribute("SampleProject")]
[assembly: AssemblyProductAttribute("SampleProject")]
[assembly: AssemblyDescriptionAttribute("SampleProject is a product of TestCompany - git@github.com:jfcantin/Playbox.git.")]
[assembly: AssemblyTrademarkAttribute("SampleProject - TestCompany")]
[assembly: AssemblyCopyrightAttribute("Copyright 2010 TestCompany, - Original author or authors")]

